### ISSUE TITLE
any update on container support in cloudsim plus ?

### ISSUE THREAD

**Issue by scethiren** [manoelcampos/cloudsim-plus-automation#8]
hi,
any update on container support in cloudsim plus ?

I need it for my research work.

good day.

**Comment by manoelcampos** [comment]
The container implementation in CloudSim has several issues since day one, which were never fixed. Just check the issues page at CloudSim's GitHub repository. 
CloudSim itself is abandoned for years. The last relevant commit was in 2016 when the container support was introduced. After that, just 5 commits were pushed without any relevant update or bug fixes.

There is no short-term intention to support containers in CloudSim Plus, unfortunately.
